name: 'Codelove Blog Updater'
description: 'Fetches blog posts from Codelove and updates README.md'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  CODELOVE_USERNAME:
    description: 'Your Codelove username'
    required: true
  CODELOVE_API_URL:
    description: 'Codelove API URL'
    required: false
    default: 'https://codelove.tw/api/posts'
  MAX_LINES:
    description: 'Maximum number of blog posts to include'
    required: false
    default: '10'
  README_START_MARKER:
    description: 'Start marker for blog posts section in README'
    required: false
    default: '<!-- UPDATE_CODELOVE:START -->'
  README_END_MARKER:
    description: 'End marker for blog posts section in README'
    required: false
    default: '<!-- UPDATE_CODELOVE:END -->'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'
    - run: bun install
      shell: bash
    - run: bun run index.js
      shell: bash

branding:
  icon: 'book'
  color: 'blue'
