name: 'Codelove Blog Updater'
description: 'Fetches blog posts from Codelove and updates README.md'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  MAX_LINES:
    description: 'Maximum number of blog posts to fetch'
    required: false
    default: '5'
  COMMITTER_USERNAME:
    description: 'Username for the commit'
    required: false
    default: 'github-actions[bot]'
  COMMITTER_EMAIL:
    description: 'Email for the commit'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  COMMIT_MSG:
    description: 'Commit message'
    required: false
    default: 'docs: update README with latest blog posts'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'book'
  color: 'blue'
