name: Test Codelove Blog Updater

# You can modify the workflow to run on different events
on:
  workflow_run:
    workflows: ['Build Action']
    types:
      - completed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Test Codelove Blog Updater
        uses: jaosn60810/readme-codelove-list@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # You can modify the CODELOVE_USERNAME to your own
          CODELOVE_USERNAME: 'jason60810'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'test: update README with latest blog posts'
          add: 'README.md'
