name: Test Codelove Blog Updater

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Codelove Blog Updater
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODELOVE_USERNAME: 'jasonmoney'
          MAX_LINES: '3'
          README_START_MARKER: '<!-- UPDATE_CODELOVE:START -->'
          README_END_MARKER: '<!-- UPDATE_CODELOVE:END -->'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'test: update README with latest blog posts'
          add: 'README.md'
