name: Test Codelove Blog Updater

# You can modify the workflow to run on different events
on:
  workflow_run:
    workflows: ['Build Action']
    types:
      - completed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: Test Codelove Blog Updater
        uses: jaosn60810/readme-codelove-list@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODELOVE_USERNAME: 'jason60810'
          MAX_LINES: '10'
          README_START_MARKER: '<!-- UPDATE_CODELOVE:START -->'
          README_END_MARKER: '<!-- UPDATE_CODELOVE:END -->'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'test: update README with latest blog posts'
          add: 'README.md'
